language: node_js
node_js:
- node
install:
- npm install
script:
- npm run build || true
deploy:
  skip_cleanup: true
  provider: npm
  email: taoabc@gmail.com
  api_key:
    secure: SNwlCRYRxshAfLdggshupCbYV0pC2qKCGERaj0sJSCozxoZPYnal9IdqYOLEVSSX6ca0yAjDcJz1Ynqgn1+VBzsJtwTRxsvmCCGnlZeME68lEiPe5j4C0ZNBn0Zne8q5IT2eOdtZuYkVQ0zruENTKhJeOY3VSUGmUSBu7aOTQ4Fhlww61dsKUdIBatvsny9jAddaJsCIAMydPYdvYmr6vA4AmGi2wwFSscCe8FYWaH4CXgkdcvLcK66d/TYAISC/SQalBikXevk4QjLqQW/r4Lx56s7HF5qRwGnUC9YQ5HT5eNR3qTXNy0yY5k/THoCekDcmOMG2/qXU4pM1jgpEkVYk/6nhycGTnr2g8lx+NYmDvOarpDmh5CQVPAEeAAtD1DRYB5gTRCZbCK+tXsncKDrDFA/8sv/dPKh4Xzsgu1KGm+eklQUCMrQWMpgmUHVaNnnBTsXVk7WNXfeSrPRFcXVcBbLIcy6WYqUsr2s0quV6KbkFIgfJSmzbNpcAmPIF/sWc4Kp36PIN4rOlaPQc1CBVcbIn2nGZpsgvB3fvfg3vJN0jYHVtz2oL0EQwDxDJ7G2HbHF1cEkL9QdE3FSyS57VugXmqJN6SHipqgRJqBPVOZhmRgx20o7Yl/x8w4pDCf0fLAR/lUPo5DeAInLk0NIjjr9fsCuoeKZ6gtpmjDs=
  on:
    tags: true
    repo: taoabc/dragonbones-phaser
